#!/usr/bin/env bash

export PS4='+${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '

function usage {
    echo "Usage: $0 <init|test|accept>"
}

function help {
    usage
}

function required {
    cat >&2 <<EOM
$0: Missing git config: $1
Try \`git config --local $1 <value>\` to set $1 for this repository.
EOM
    exit 2
}

function config {
    local opts=(--get)
    while (( 0 < $# ))
    do
        case $1 in
            --bool ) opts=("${opts[@]}" $1) ; shift ;;
            -* ) echo "$0: BUG" >&2 ; exit 3 ;;
            * ) break ;;
        esac
    done
    local config=tdd.$1
    git config "${opts[@]}" $config 2>/dev/null || echo "${2-required $config}"
}

function init {
    while (( 0 < $# ))
    do
        case $1 in
            --help ) usage ; exit 0 ;;
            * ) usage >&2 ; exit 2 ;;
        esac
    done
    current="$(git log -1 --pretty=%s)"
    initial="$(config initMessage WIP)"
    if [[ "$initial" == "$current" ]]
    then
        echo "$0: Already initialized: $current" >&2
        exit 2
    fi
    if ${FIRST_TIME-true}
    then
        cat <<EOM
Initial commit message (git config tdd.initMessage): $initial
Pull before test (git config tdd.pullBeforeTest): true
Test command (git config --local tdd.testCommand): $(config testCommand)
Accept command (git config --local tdd.acceptCommand): $(config acceptCommand)
EOM
        {
            git stash
            git commit --allow-empty -m "$initial"
            git stash pop
        } >/dev/null
    else
        git commit --allow-empty -m "$initial" >/dev/null
    fi
}

function test {
    while (( 0 < $# ))
    do
        case $1 in
            --help ) usage ; exit 0 ;;
            * ) usage >&2 ; exit 2 ;;
        esac
    done
    if $(config --bool pullBeforeTest true)
    then
        # Support older git without `git pull --autostash`
        # See http://stackoverflow.com/questions/30208928/can-git-pull-automatically-stash-and-pop-pending-changes
        # TODO: Support even older git (see http://stackoverflow.com/a/31575425)
        git -c rebase.autoStash=true pull --rebase || return $? 
    fi >/dev/null
    $(config testCommand) \
        && git commit -a --amend --no-edit >/dev/null
}

function accept {
    while (( 0 < $# ))
    do
        case $1 in
            --help ) usage ; exit 0 ;;
            -m ) local message="$2" ; shift 2 ;;
            * ) usage >&2 ; exit 2 ;;
        esac
    done
    $(config acceptCommand) \
        && git commit -a --amend ${message+-m "$message"} \
        && git push \
        && FIRST_TIME=false init
}

while (( 0 < $# ))
do
    case $1 in
        --help ) exec man ${0##*/} ;;
        -* ) usage >&2 ; exit 2 ;;
        * ) break ;;
    esac
done

case $# in
    0 ) usage >&2 ; exit 2 ;;
esac

case $1 in
    init | test | accept ) "$@" ;;
    * ) usage >&2 ; exit 2 ;;
esac
