#!/bin/bash

export PS4='+${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '

truecolor=true
while getopts :68-: opt
do
    [[ - == $opt ]] && opt="${OPTARG%%=*}" OPTARG="${OPTARG#*=}"
    case $opt in
    6 | 256-color ) truecolor=false ;;
    8 | truecolor ) truecolor=true ;;
    esac
done
shift $(( OPTIND - 1 ))

pbold=$(printf '\e[1m')
plight=$(printf '\e[2m')
pitalic=$(printf '\e[3m')
punderscore=$(printf '\e[4m')
pblink=$(printf '\e[5m')
preverse=$(printf '\e[7m')
pinvisible=$(printf '\e[8m')
pstrikethrough=$(printf '\e[9m')

declare -a effects
for v in ${!p*}
do
    effects+=(${v#p})
done

preset=$(printf '\e[0m')

pblack=$(printf '\e[30m')
pred=$(printf '\e[31m')
pgreen=$(printf '\e[32m')
pyellow=$(printf '\e[33m')
pblue=$(printf '\e[34m')
pmagenta=$(printf '\e[35m')
pcyan=$(printf '\e[36m')
pwhite=$(printf '\e[37m')
printf $preset

for e in ${effects[*]}
do
    echo This is $e
    for c in black red green yellow blue magenta cyan white
    do
        eval "printf \" \${p$e}\${p$c}$c\$preset\""
    done
    echo
done
echo Done

{
    pushd $(dirname $0)
    root_dir=$(pwd -P)
    popd
} >/dev/null

: ${X11_RGB_TXT:=/usr/share/X11/rgb.txt}
[[ -r $X11_RGB_TXT ]] || X11_RGB_TXT=$root_dir/rgb.txt

if declare -A fg_colors 2>/dev/null
then
    readonly cached_colors=true
    declare -A bg_colors
else
    readonly cached_colors=false
fi

function _copy_f {
    eval function $2 "$(declare -f $1 | sed 1d)"
}

function _truecolor_fg {
    printf '\e[38;2;%d;%d;%dm' $1 $2 $3
}

function _truecolor_bg {
    printf '\e[48;2;%d;%d;%dm' $1 $2 $3
}

function _256color_d {
    local -r r=$(( 5 * $1 / 255 ))
    local -r g=$(( 5 * $2 / 255 ))
    local -r b=$(( 5 * $3 / 255 )) 
    return $(( (36 * r) + (6 * g) + b + 16 ))
}

function _256color_fg {
    _256color_d $1 $2 $3
    local -r rgb=$?
    printf '\e[38;5;%dm' $rgb
}

function _256color_bg {
    _256color_d $1 $2 $3
    local -r rgb=$?
    printf '\e[48;5;%dm' $rgb
}

function _to_rgb {
    while read r g b name
    do
        [[ -z "$name" ]] && name="$b" b=0
        if [[ "$name" == "$1" ]]
        then
            echo $r $g $b
            return
        fi
    done <$X11_RGB_TXT
    echo "$0: $FUNCNAME: Unknown color: $1" >&2
    exit 2
}

if $truecolor
then
    _copy_f _truecolor_fg _fg
    _copy_f _truecolor_bg _bg
else
    _copy_f _256color_fg _fg
    _copy_f _256color_bg _bg
fi
unset -f _truecolor_fg _truecolor_bg _256color_fg _256color_bg

if $cached_colors
then
    while read r g b name
    do
        [[ -z "$name" ]] && name="$b" b=0
        # Inline _fg and _bg for performance
        if $truecolor
        then
            fg_colors[$name]="\e[38;2;$r;$g;${b}m"
            bg_colors[$name]="\e[48;2;$r;$g;${b}m"
        else
            r=$(( 5 * r / 255 ))
            g=$(( 5 * g / 255 ))
            b=$(( 5 * b / 255 )) 
            rgb=$(( (36 * r) + (6 * g) + b + 16 ))
            fg_colors[$name]="\e[38;5;${rgb}m"
            bg_colors[$name]="\e[48;5;${rgb}m"
        fi
    done <$X11_RGB_TXT
fi

function c {
    case $# in
    1 | 3 ) set -- fg "$@" ;;
    2 | 4 ) case $1 in
        fg | bg ) ;;
        * ) echo "Usage: $0: $FUNCNAME [fg|bg] <named-color|red8 green8 blue8>" >&2
            exit 2 ;;
        esac ;;
    * ) echo "Usage: $0: $FUNCNAME [fg|bg] <named-color|red8 green8 blue8>" >&2
        exit 2 ;;
    esac

    local r g b
    case $2 in
    [0-9]* ) r=$2 g=$3 b=$3 ;;
    * ) if $cached_colors
        then
            case $1 in
            fg ) printf ${fg_colors[$2]} ;;
            bg ) printf ${bg_colors[$2]} ;;
            esac
            return
        else
            read r g b < <(_to_rgb "$2")
        fi ;;
    esac
    readonly r g b
    case $1 in
    fg ) _fg $r $g $b ;;
    bg ) _bg $r $g $b ;;
    esac
}

for r in $(seq 5 10 255)
do
    c bg $r 0 0
    printf '  '
done
printf '\e[0m\n'

for color
do
    printf "$(c $color)$color$preset\n"
done
