#!/bin/bash

export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}():} '

set -e
set -o pipefail

curl_args=()
for arg
do
    case "$arg" in
    -- ) shift ; break ;;
    * ) curl_args=("${curl_args[@]}" "$arg") ; shift ;;
    esac
done
head_args=-D-
for curl_arg in "${curl_args[@]}"
do
    case "$curl_arg" in
    -I | --head ) head_args= ;;
    esac
done

jq_args=("${@-.}")

# TODO: Heuristic, need to parse JQ args for options
color=false
[[ -t 1 ]] && color=true
[[ "${jq_args[@]}" =~ -([a-z][A-Z])*C([a-z][A-Z])* ]] && color=true
[[ "${jq_args[@]}" =~ -([a-z][A-Z])*M([a-z][A-Z])* ]] && color=false

curl -s $head_args "${curl_args[@]}" | tr -d '\r' | {
    json=false
    first=$color
    shopt -s nocasematch
    while read line
    do
        $first && {
            first=false
            printf "\e[1m$line\e[0m\n" "$line"
            continue
        }
        [[ -z "$line" ]] && { echo ; break ; }
        [[ "$line" =~ ^Content-Type:.*json ]] && json=true
        printf "%s\n" "$line"
    done

    if $json
    then
        jq "${jq_args[@]}"
    else
        if ((0 < $#))
        then
            echo "$0: jq arguments for non-JSON response: $@" >&2
            exit 2
        fi

        cat
    fi
}
