#!/bin/bash

set -o errexit
set -o errtrace
set -o pipefail

let pass=0 fail=0 error=0 && true

function pass {
    local message="$1"
    echo "$0: $test_name: $message"
    let ++pass
}

function fail {
    local message="$1"
    echo "$0: $test_name: $message" >&2
    let ++fail
}

function error {
    local message="$1"
    echo "$0: $test_name: $message: $scenario_text" >&2
    let ++error
}
