#!/bin/bash

function setup_repo_and_clones {
    svnadmin create mergey
    svn co file://$root/mergey svn
    pushd svn
    svn mkdir trunk tags branches
    svn commit -m 'Standard layout'
    popd
    # All repos start with 1 common commit
    and_commit_in svn_trunk 'foo' 'Common commit'
    git svn clone -s file://$root/mergey git
}

function setup_branch {
    svn copy file://$root/mergey/trunk file://$root/mergey/branches/develop -m 'Branch develop'
    pushd svn
    svn up
    popd
    pushd git
    git svn fetch --fetch-all
    popd
}

function trunk {
    case $# in
    3 ) ;;
    * ) error 'Missing commit details for trunk' ;;
    esac

    local file=$1
    local message=$2
    local content=$3
    shift 3
}

function svn_commit {
    local dir=$1
    local file=$2
    local commit_message=$3
    local contents=$4

    pushd svn/$dir
    echo "$contents" >$file
    svn add $file
    svn commit -m "$commit_message"
    popd
}

function git_commit {
    local branch=$1
    local file=$2
    local commit_message=$3
    local contents=$4

    pushd git
    git checkout $branch
    echo "$contents" >$file
    git add $file
    git commit $file -m "$commit_message"
    popd
}

function svn_trunk {
    case $# in
    2 | 3 ) local file=$1 commit_message=$2 contents=$3 ;;
    * ) error 'No file and commit message and contents for svn_trunk' ;;
    esac

    svn_commit trunk $file "$commit_message" "$contents"
}

function svn_branch {
    case $# in
    2 | 3 ) local file=$1 commit_message=$2 contents=$3 ;;
    * ) error 'No file and commit message and contents for svn_branch' ;;
    esac

    svn_commit branches/develop $file "$commit_message" "$contents"
}

function git_trunk {
    case $# in
    2 | 3 ) local file=$1 commit_message=$2 contents=$3 ;;
    * ) error 'No file and commit message and contents for git_trunk' ;;
    esac

    git_commit master $file "$commit_message" "$contents"
}

function git_branch {
    case $# in
    2 | 3 ) local file=$1 commit_message=$2 contents=$3 ;;
    * ) error 'No file and commit message and contents for git_branch' ;;
    esac

    git_commit develop $file "$commit_message" "$contents"
}

function and_commit_in {
    case $1 in
    svn_trunk | svn_branch | git_trunk | git_branch ) "$@" ;;
    * ) error 'No svn_trunk or svn_branch or git_trunk or git_branch for and_commit_in' ;;
    esac
}

function and_no_changes {
    pass 'TODO: Check git HEAD hashes that nothing happened'
}

function then_exit {
    local actual=$1
    local expected=$2
    shift 2

    if (( actual == expected ))
    then
        "$@"
    else
        fail "Wrong exit code when merging: expected $expected, got $actual"
    fi
}

function merge_develop_from_master {
    pushd
    git checkout develop
    git merge-svn -i master
    local code=$?
    popd
    return $code
}

function when_merge {
    merge_develop_from_master
    code=$?

    case $1 in
    then_exit ) shift ; then_exit $code "$@" ;;
    * ) error 'No then_exit for when_merge' ;;
    esac
}

function given_repo {
    setup_repo_and_clones
    setup_branch

    case $1 in
    and_commit_in | when_merge ) "$@" ;;
    * ) error 'No and_commit_in or when_merge for given_repo' ;;
    esac
}

function scenario {
    local scenario_text="scenario $@"
    local test_name='<UNKNOWN>'

    case $# in
    0 | 1 ) error 'Malformed scenario' ;;
    * ) test_name="$1" ; shift ;;
    esac

    case $1 in
    given_repo ) "$@" ;;
    * ) error 'No given_repo for scenario' ;;
    esac
}



function commit_on_trunk_only {
    pushd git
    touch bar
    git add bar
    git commit -a -m 'Trunk only commit'
    git svn dcommit
    popd
}
commit_on_trunk_only

function setup_git_branch {
    pushd git
    git svn fetch --fetch-all
    git checkout develop remotes/origin/develop
    popd
}
setup_git_branch

function commit_on_branch_only {
    pushd git
    git checkout develop
    touch baz
    git add baz
    git commit -a -m 'Branch only commit'
    git svn dcommit
    popd
}
commit_on_branch_only

function commit_conflict {
    pushd git
    git checkout master
    echo 'Trunk conflict' >foo
    git commit -a -m 'Trunk conflict'
    git svn dcommit

    git checkout develop
    echo 'Branch conflict' >foo
    git commit -a -m 'Branch conflict'
    git svn dcommit
    popd
}
commit_conflicts

function commit_trunk_only_again {
    pushd git
    git checkout master
    echo 'Trunk update' >bar
    git commit -a -m 'Trunk update'
    git svn dcommit
    popd
}
commit_trunk_only_again

function commit_branch_only_again {
    pushd git
    echo 'Branch update' >bar
    git commit -a -m 'Branch update'
    git svn dcommit
    popd
}
commit_trunk_only_again


merge_develop_from_master
bash
