#!/bin/bash

export PS4='+${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '

{
    pushd $(dirname $0)
    root_dir=$(pwd -P)
    popd
} >/dev/null

: ${X11_RGB_TXT:=/usr/share/X11/rgb.txt}
[[ -r $X11_RGB_TXT ]] || X11_RGB_TXT=$root_dir/rgb.txt

c_truecolor=true
while getopts :68-: opt; do
    [[ - == $opt ]] && opt="${OPTARG%%=*}" OPTARG="${OPTARG#*=}"
    case $opt in
    6 | 256-color) c_truecolor=false ;;
    8 | c_truecolor) c_truecolor=true ;;
    esac
done
shift $((OPTIND - 1))

. $root_dir/color.sh

function echo_with_ascii_formatting() {
    local text="$1" ; shift

    echo -n "$preset"
    for x ; do eval echo -n "\$p$x" ; done
    echo -n "$preset"
}

echo This is normal color
for c in black red green yellow blue magenta cyan white; do
    eval "echo -n \" \${p$c}$c\$preset\""
done
echo
for e in bold light italic underline blink reverse invisible strikethrough; do
    echo This is $e color
    for c in black red green yellow blue magenta cyan white; do
        eval "echo -n \" \${p$e}\${p$c}$c\$preset\""
    done
    echo
done
echo

for r in $(seq 5 10 255); do
    c bg $r 0 0
    printf '  '
done
echo "$preset"
for g in $(seq 5 10 255); do
    c bg 0 $g 0
    printf '  '
done
echo "$preset"
for b in $(seq 5 10 255); do
    c bg 0 0 $b
    printf '  '
done
echo "$preset"

for color; do
    printf "$(c $color)$color$preset\n"
done

echo These are ASCII escape codes for the terminal, including oddballs
echo Please be cautious: most users just want bold and color
text='FRODO LIVES!'
for x in reset bold light italic underline blink rapidblink reverse \
    invisible strikethrough doubleunderline; do
    eval "echo \"  ${x^^}: \$preset\${p$x}\$text\$preset\""
done

echo If your terminal has multiple fonts, though poorly supported
for x in primary {11..19} fraktur; do
    eval "echo \"  FONT ${x^^}: \$preset\${p${x}font}\$text\$preset\""
done

echo Mixing together
echo_with_ascii_formatting "$text" bold light italic underline blink reverse \
    strikethrough green
echo Mixing together, removing all but color
echo Need more research on meaning of \"Normal intensity\"
echo_with_ascii_formatting "$text" bold light italic underline blink reverse \
    strikethrough green normal

echo Undo underline only
echo -n "$pyellow"
echo -n "$punderline"
echo "$text"
echo -n "$pnounderline"
echo "$text"
echo -n "$preset"
